# Generated by Django 3.1.3 on 2020-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('title_english', models.CharField(max_length=200)),
                ('title_long', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('genres', models.CharField(max_length=200)),
            ],
        ),
    ]
